#! /bin/bash
echo "Building with maven..."
cd $OPENSHIFT_REPO_DIR
mvn -s $OPENSHIFT_REPO_DIR/.openshift/settings.xml -q package
cp target/hackwlb-server.jar server.jar

echo "Removing useless files..."
rm -rf $(ls -A | sed -n '/^\.openshift$/!{/^server\.jar$/!p}')

md5sum server.jar
echo "Done!"
