#!/bin/bash
export NMG_CONFIG="$OPENSHIFT_DATA_DIR/.nmg-config"
nohup java -jar $OPENSHIFT_REPO_DIR/server.jar $OPENSHIFT_NGINX_IP 8123 |& /usr/bin/logshifter -tag hackwlb &

echo "Application started"
